DROP TABLE IF EXISTS OldValues;
CREATE TABLE OldValues (timeStamp BIGINT, tagValue INT, tagName STRING)
	ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';
LOAD DATA INPATH 'data/data.dat' OVERWRITE INTO TABLE OldValues;
